import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { trpcClientComp } from '@/server/trpc.Provider';
import { httpBatchLink } from '@trpc/client';
import { Providers } from "./Providres";
import { NavBar } from "@/components/ui/NavBar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  const trpcClient = trpcClientComp.createClient({
    links: [
      httpBatchLink({ url: '/api/trpc' }),
    ],
  });

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Providers>
          <header className="h-[8vh] w-full bg-gray-800 py-2 flex items-center">
            <NavBar />
          </header>
          <main className="flex-1">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}