import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "../providers/Providres";
import { NavBar } from "@/components/ui/NavBar";

import {AppToaster} from "@/providers/ToastProvider"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Providers>
          <header className="h-auto min-h-[9vh] w-full bg-gray-900 py-2 sm:py-3 md:py-4 flex items-center border-b-2 border-b-purple-600">
            <NavBar />
          </header>
          <main className="flex-1 bg-gray-900 pt-12 sm:pt-0 ">
            {children}
            <AppToaster />
          </main>
        </Providers>
      </body>
    </html>
  );
}